### ISSUE TITLE
breaking changes in wagmi

### ISSUE THREAD

**Issue by pbfranceschin** [eth-infinitism/trampoline#22]
i see you updated wagmi to the newest version. versions above 1 don't support hooks like useProvider present in this code base. there are a couple of other hooks that are not supported in the newer versions. checkout the breaking changes [here](https://wagmi.sh/react/migration-guide)

**Comment by pbfranceschin** [comment]
i think if you change useProvider to usePublicClient should be enough. did not test yet.

**Comment by plusminushalf** [comment]
Fixed with https://github.com/eth-infinitism/trampoline/commit/cb782f83912d25db3dccf3924e4de9c56cd1f2cf
